### PR TITLE
Changed region name

### PR DESCRIPTION
**Pull request by greengazebo**
Changed region name to more acuratly represent what it does. Small bugifx that I need to submit for personal reasons.

### CODE REVIEW

**Comment by PoroCYon** [comment]
Wow, you still care about this?

Anyway, I'd merge this, but it seems that I somehow lost write access to the repo >__>

Edit: ping @Meowmaritus ?

**Comment by Meowmaritus** [comment]
> Wow, you still care about this?
> 
> Anyway, I'd merge this, but it seems that I somehow lost write access to the repo >__>
> 
> Edit: ping @Meowmaritus ?

I don't have write access either.

**Comment by PoroCYon** [comment]
Hrmmm... @MageKing17 @RawringNymNym ?

**Comment by ghost** [comment]
Huh interesting...

Didn't think I'd have it :joy:

**Comment by MageKing17** [comment]
Seems I also have write access, though.

EDIT: And so do @Nopezal and @RawringNymNym. I could probably see about adding you guys if you wanted?

**Pull request merged**
