### PR TITLE
Add a hook for potentially altering which music Terraria wants to play.

### PR DESCRIPTION
**Pull request by MageKing17**
Plus a couple minor cleanup commits. The primary commit is e068a7f, which adds the hook and injects an entry point for it into Terraria.Main.UpdateMusic().

The implementation is... somewhat messy. I must admit to a feeling of flailing around in the dark, and the documentation is lacking. If somebody knows a cleaner way to do it, I'm all ears. Still, it _does_ work.

### CODE REVIEW

**Comment by MRokas** [comment]
Suggestion: MusicDef - let add own music. Shouldn't be that hard to do I guess. Would do myself, but before I learn enough c#, it will be more than done so.. :D

**Comment by PoroCYon** [comment]
It might be a better idea to just rewrite UpdateMusic so the whole system has proper priority etc. support, and will be easier to support custom music (and proper conditions, eg. "is in biome _", "boss _ is near", etc.)

**Comment by MageKing17** [comment]
MusicDef implementation, done right, would definitely be nontrivial; at least as hard as trying to increase, say, the number of NPCs that can be simultaneously active. Without decompiling, finding and changing all the appropriate magic number references would be... involved. A better bet might be stopping regular in-game music and then start playing the custom song you want.

Possibly easier: wave bank selector.

**Comment by MageKing17** [comment]
Rewriting UpdateMusic altogether gets you more features, of course, but means you can't reuse the original in any meaningful way.

**Comment by PoroCYon** [comment]
I've wandered enough in the UpdateMusic code (in earlier version of Terraria), I know how it works. Also, the current implementation only supports vanilla music.

**Comment by MageKing17** [comment]
What I mean is that a custom UpdateMusic implementation gets you no advantage from Prism's Cecil-based approach; if Re-Logic adds another song, the custom UpdateMusic will need updating (but hooks like this may still work correctly).

Of course it can be done and could result in the most features with the best performance; it's just harder to maintain.

**Comment by PoroCYon** [comment]
Not always harder to maintain if done properly. The current (vanilla) UpdateMusic implementation makes it a little hard to do that already. If a proper API can be used, every new song will only require one extra line, somewhere. (The current implementation is a mess of deeply nested if/else-ifs.)

Or, we could preserve the vanilla code and wrap around it, à la SetDefaults/RealSetDefaults/OnSetDefaults.

**Pull request merged**
