### PR TITLE
Added mod Tile base

### PR DESCRIPTION
**Pull request by Neojin9**

### CODE REVIEW

**Comment by PoroCYon** [comment]
This is huge, and hard to see what's exactly changed.

**Comment by MRokas** [comment]
I'm pretty sure most of those changes are just forked/pulled files, and he accidentally PR'ed them all.

I'm pretty sure intended push was this:

https://github.com/TerrariaPrismTeam/Prism/commit/d8410eac51041f819dd0709f25ef825f198642ff

**Comment by Neojin9** [comment]
MRokas you are completely right!

I cloned the repository into a shared Cloud9 project, and set up git there. I made my files, then did a commit and push.

The push had my girlfriend has the author/commitor. I tried to fix the issue myself and ended up modifying all previous commits to have me as the author. I didn't know this though. Then my girlfriend fixed the initial problem, and I created the PR. After which I noticed the mistake I had caused. 

That's when I told Poro I had messed up and to ignore my PR.

I worked a lot on creating the base for mod tile support, and I hate for that work to go to waste, but I don't want to cause any issue for the team. 

I wanted so badly to be a contributor to the project. I really appreciate the work that's being done here.

**Comment by MRokas** [comment]
Your original PR for TileDef is still there, so lets hope @PoroCYon will check it - 

https://github.com/TerrariaPrismTeam/Prism/commit/d8410eac51041f819dd0709f25ef825f198642ff

**Comment by MageKing17** [comment]
Use git cherry-pick to recreate the PR with only that one commit.

**Pull request closed without merging**
